# # ---------- Build Stage ----------
# FROM maven:3.9.6-eclipse-temurin-17 AS build
# WORKDIR /app
# COPY . .
# RUN mvn clean package -DskipTests

# # ---------- Run Stage ----------
# FROM eclipse-temurin:17-jdk-jammy
# WORKDIR /app
# COPY --from=build /app/target/*.jar app.jar

# ENTRYPOINT ["java", "-jar", "app.jar"]
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY backend/ .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]